from fpdf import FPDF
from datetime import datetime

class StockReportPDF(FPDF):
    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=12)

    def header(self):
        self.set_font("Helvetica", "B", 14)
        self.cell(0, 8, "DAILY INDIAN STOCK MARKET REPORT", 0, 1, "C")
        self.set_font("Helvetica", "", 9)
        self.cell(0, 5, f"Analysis Date: {datetime.now().strftime('%d %B %Y | %H:%M IST')}", 0, 1, "C")
        self.cell(0, 5, "Real Data Analysis | Medium-Risk Portfolio", 0, 1, "C")
        self.ln(3)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(3)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "I", 7)
        self.cell(
            0, 5,
            f"Page {self.page_no()}/4 | Auto-generated by Stock Agent | Not Investment Advice",
            0, 0, "C"
        )

    def chapter_title(self, title: str):
        self.set_font("Helvetica", "B", 12)
        self.set_fill_color(220, 220, 220)
        self.cell(0, 7, title, 0, 1, "L", True)
        self.ln(2)

    def body_text(self, text: str):
        self.set_font("Helvetica", "", 8.5)
        safe = text.encode("latin-1", "replace").decode("latin-1")
        self.multi_cell(0, 4, safe)

def create_pdf(intraday_text: str, portfolio_text: str) -> str:
    """Generate 4-page PDF report with REAL data"""
    pdf = StockReportPDF()

    intraday_lines = intraday_text.split("\n")
    portfolio_lines = portfolio_text.split("\n")
    
    mid1 = len(intraday_lines) // 2
    mid2 = len(portfolio_lines) // 2

    pdf.add_page()
    pdf.chapter_title("PART 1: MARKET OVERVIEW & INDICES")
    pdf.body_text("\n".join(intraday_lines[:mid1]))

    pdf.add_page()
    pdf.chapter_title("PART 2: SECTOR ANALYSIS & TRADING STRATEGY")
    pdf.body_text("\n".join(intraday_lines[mid1:]))

    pdf.add_page()
    pdf.chapter_title("PART 3: MEDIUM-RISK STOCK RECOMMENDATIONS")
    pdf.body_text("\n".join(portfolio_lines[:mid2]))

    pdf.add_page()
    pdf.chapter_title("PART 4: PORTFOLIO ALLOCATION & ENTRY LEVELS")
    pdf.body_text("\n".join(portfolio_lines[mid2:]))

    filename = f"stock_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    pdf.output(filename)
    return filename
