"""
Indian Stock Universe (NSE) for analysis.
You can expand this list later; core indices already give wide coverage.
"""

NIFTY_50 = [
    'RELIANCE.NS', 'TCS.NS', 'HDFCBANK.NS', 'INFY.NS', 'ICICIBANK.NS',
    'HINDUNILVR.NS', 'SBIN.NS', 'BHARTIARTL.NS', 'KOTAKBANK.NS', 'ITC.NS',
    'LT.NS', 'AXISBANK.NS', 'ASIANPAINT.NS', 'MARUTI.NS', 'SUNPHARMA.NS',
    'TITAN.NS', 'ULTRACEMCO.NS', 'NESTLEIND.NS', 'WIPRO.NS', 'HCLTECH.NS',
    'BAJFINANCE.NS', 'POWERGRID.NS', 'NTPC.NS', 'TATASTEEL.NS', 'ONGC.NS',
    'JSWSTEEL.NS', 'M&M.NS', 'TATAMOTORS.NS', 'ADANIENT.NS', 'ADANIPORTS.NS',
    'COALINDIA.NS', 'BAJAJFINSV.NS', 'GRASIM.NS', 'TECHM.NS', 'INDUSINDBK.NS',
    'HINDALCO.NS', 'DRREDDY.NS', 'DIVISLAB.NS', 'CIPLA.NS', 'BRITANNIA.NS',
    'EICHERMOT.NS', 'APOLLOHOSP.NS', 'HEROMOTOCO.NS', 'BPCL.NS', 'TATACONSUM.NS',
    'SBILIFE.NS', 'HDFCLIFE.NS', 'BAJAJ-AUTO.NS', 'SHRIRAMFIN.NS', 'LTIM.NS'
]

NIFTY_NEXT_50 = [
    'ADANIGREEN.NS', 'AMBUJACEM.NS', 'AUROPHARMA.NS', 'BANKBARODA.NS', 'BEL.NS',
    'BERGEPAINT.NS', 'BOSCHLTD.NS', 'CANBK.NS', 'CHOLAFIN.NS', 'COLPAL.NS',
    'DLF.NS', 'DABUR.NS', 'GAIL.NS', 'GODREJCP.NS', 'HAVELLS.NS',
    'HDFCAMC.NS', 'ICICIGI.NS', 'ICICIPRULI.NS', 'IGL.NS', 'INDHOTEL.NS',
    'INDIGO.NS', 'IOC.NS', 'IRCTC.NS', 'JINDALSTEL.NS', 'JUBLFOOD.NS',
    'LUPIN.NS', 'MARICO.NS', 'MCDOWELL-N.NS', 'MOTHERSON.NS', 'MUTHOOTFIN.NS',
    'NAUKRI.NS', 'NHPC.NS', 'NMDC.NS', 'OFSS.NS', 'PAGEIND.NS',
    'PIDILITIND.NS', 'PNB.NS', 'RECLTD.NS', 'SBICARD.NS', 'SIEMENS.NS',
    'SRF.NS', 'TATAPOWER.NS', 'TORNTPHARM.NS', 'TRENT.NS', 'VEDL.NS',
    'VBL.NS', 'ZOMATO.NS', 'ZYDUSLIFE.NS'
]

NIFTY_MIDCAP_EXTRA = [
    'ACC.NS', 'ASHOKLEY.NS', 'AUBANK.NS', 'BALKRISIND.NS', 'BATAINDIA.NS',
    'BHARATFORG.NS', 'BIOCON.NS', 'CANFINHOME.NS', 'CROMPTON.NS', 'CUMMINSIND.NS',
    'DEEPAKNTR.NS', 'DIXON.NS', 'ESCORTS.NS', 'EXIDEIND.NS', 'FEDERALBNK.NS',
    'FORTIS.NS', 'GLAND.NS', 'GODREJPROP.NS', 'GUJGASLTD.NS', 'IDFCFIRSTB.NS',
    'INDIANB.NS', 'INDUSTOWER.NS', 'IRFC.NS', 'JSWENERGY.NS', 'KAJARIACER.NS',
    'KEI.NS', 'LICHSGFIN.NS', 'LTTS.NS', 'M&MFIN.NS', 'MAXHEALTH.NS',
    'MCX.NS', 'MGL.NS', 'MPHASIS.NS', 'NAVINFLUOR.NS', 'NATIONALUM.NS',
    'OBEROIRLTY.NS', 'PERSISTENT.NS', 'PETRONET.NS', 'PFC.NS', 'POLYCAB.NS',
    'POONAWALLA.NS', 'PRESTIGE.NS', 'PVRINOX.NS', 'RBLBANK.NS', 'SHREECEM.NS',
    'SJVN.NS', 'STARHEALTH.NS', 'SUNDRMFAST.NS', 'SUPREMEIND.NS', 'TATACHEM.NS',
    'TATACOMM.NS', 'TATAELXSI.NS', 'TORNTPOWER.NS', 'TVSMOTOR.NS', 'UNIONBANK.NS',
    'UPL.NS', 'VOLTAS.NS'
]

STOCK_UNIVERSE = sorted(list(set(NIFTY_50 + NIFTY_NEXT_50 + NIFTY_MIDCAP_EXTRA)))


